export const LOAD_TRACKS_PENDING = "LOAD_TRACKS_PENDING";
export const LOAD_TRACKS_SUCCESS = "LOAD_TRACKS_SUCCESS";
export const LOAD_TRACKS_FAILURE = "LOAD_TRACKS_FAILURE";

export const SELECT_TRACK = "SELECT_TRACK";
